### PR TITLE
add cost page

### PR DESCRIPTION
**Pull request by ddollar**
screen shot 2016-05-16 at 10 37 08 am

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jDRKywWJ&#x2F;135-pricing"> pricing</a>

**Comment by rcaught** [comment]
Suggestion:  If you use the term Pricing, instead of Cost it will be more inline with other products.

I usually think of the associated costs with the product when I see the word costs.  In Convox's case, costs are/could be the word used when talking about the related (but separate) AWS charges for minimum viable setups.

**Comment by mattmanning** [comment]
Rebased this onto master and updated the layout setting in the frontmatter for the cost page, but it still needs some more updates. Parking again temporarily.

**Comment by nzoschke** [comment]
👍 @ddollar any other thoughts before I release this?

**Comment by nzoschke** [comment]
I'm doing the layout work here. Any more copy thoughts?

**Comment by ddollar** [comment]
Will want to tweak the support stuff eventually but GTG for now

**Comment by nzoschke** [comment]
I'm working on a bit more copy and functionality before shipping. Calls to action:

* Sign Up
* Contact Us
* Slack
* Newsletter

screen shot 2016-07-16 at 12 27 21 pm

**Pull request merged**
