### PR TITLE
Activate docs search field with /

### PR DESCRIPTION
**Pull request by soulshake**
- Activate search field when user types a slash
- Remove focus when user hits <ESC>
- Slightly restyle search field

## Release Playbook
- [ ] Rebase against master
- [ ] Code review
- [ ] Merge into master
- [ ] Verify changes at http://site-staging.convox.com
- [ ] Promote release on `site-production` in the `convox/production` Rack

### CODE REVIEW

**Comment by soulshake** [comment]
[Doc search keyboard shortcut](https://trello.com/c/WsaW0pxO/1704-doc-search-keyboard-shortcut)

**Comment by ddollar** [comment]
Does this affect things like vimperator?

**Comment by soulshake** [comment]
@ddollar I have no idea. It looks like there was [an issue](https://github.com/vimperator/vimperator-labs/issues/342) but that it's been resolved?

I do know how annoying it is when sites hijack keystrokes to a search field, which is why I limited it to `/` instead of just sending all keystrokes to the search field (and made sure that `ESC` unfocuses it). I have a personal preference for `/`, but it turns out to be an issue, we could easily switch to another keycode, like `?`.

**Comment by devgh** [comment]
Hi Amy, hi David, if you are going to implement this feature, I would go with "/" because its used on Twitter and Gmail and probably on other large websites for activating the search field.  
From a UX perspective I'm a little bit skeptical about wether its a good idea in general to force any (non standardized) keystroke behavior on a user at this (high level) stage (general, international, cross plattform and cross browser website). On a german keyboard / is only available via "SHIFT + 7". So I might probalby never ever use that particular keyboard shortcut.

How are you going to notify the user about the keyboard shortcut?

Maybe its worth to check out [Mousetrap](https://craig.is/killing/mice) for a quick and easy way to implement it.

**Comment by soulshake** [comment]
@devgh as someone who searches the docs a lot, I find myself _really_ wishing for a way to activate the search field without resorting to a mouse (on this, as on other websites).

I agree that `/` is standard (if not standardized), and feel sorry for unfortunate AZERTY users in that regard.

As for how to notify the user about the keyboard shortcut: I don't have a really good idea in mind, but thought maybe we could put something in the grayed-out text in the field, like `Type '/' to search docs...` instead of just`Search docs...`.

In the future, if we ever add keyboard shortcuts to console.convox.com, we could have an overlay that appears when you type `?` like on other websites. But I don't think that's a priority today.

P.S. Danke für die Javascript-Unterstützung @devgh :)

**Pull request merged**
