### PR TITLE
[WIP] UDP support + `convox.balancer` 

### PR DESCRIPTION
**Pull request by spencerhakim**
First draft. Might benefit from added emphasis or warning blocks or something.

### CODE REVIEW

**Comment by soulshake** [comment]
[Document UDP support and convox.balancer label](https://trello.com/c/T9XWxY6F/1774-document-udp-support-and-convox-balancer-label)

**Comment by soulshake** [comment]
@spencerhakim could you please remove `.editorconfig` and rebase? Thanks!

**Comment by spencerhakim** [comment]
@soulshake Done.

**Comment by advance512** [comment]
Did this break envvar based linking?

**Pull request merged**
