### PR TITLE
Add new page about convox proxy; link to it from about-resources.md.

### PR DESCRIPTION
**Pull request by soulshake**
## Release Playbook
- [ ] Rebase against master
- [ ] Code review
- [ ] Merge into master
- [ ] Verify changes at http://site-staging.convox.com
- [ ] Promote release on `site-production` in the `convox/production` Rack

### CODE REVIEW

**Comment by soulshake** [comment]
[proxy commands](https://trello.com/c/DIrywuOG/1585-proxy-commands)

**Comment by mwarkentin** [comment]
@nduthoit has been doing some neat stuff w/ `convox proxy` and ansible for DB management (automated credential rotation, etc.) - maybe he'd be interested in blogging about it at some point. 😄

**Comment by mattmanning** [comment]
@mwarkentin Yes, please :) He can contact me directly via email or Slack DM if he wants help getting that on our blog.

**Comment by soulshake** [comment]
@mattmanning 
My bad, I used redis instead of postgres in my examples just because that's what i had handy in an example app. If you want I can replace with something similar for Postgres/psql.
Also, let me know if you think the second example doesn't cover the nonstandard local port thing you mentioned well enough.

**Comment by mattmanning** [comment]
@soulshake Redis is totally fine, too. Thanks.

**Pull request merged**
