### PR TITLE
high availability doc

### PR DESCRIPTION
**Pull request by ddollar**

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;X6tmK86Y&#x2F;74-high-availability-doc"> high availability doc</a>

**Comment by nzoschke** [comment]
Private networking and high availability don't go together in my mind

**Comment by nzoschke** [comment]
There's also something important in how we execute instance updates and deploys. We don't take anything bad down until something good came up.

**Comment by nzoschke** [comment]
Load balancers and health checks are a key part of HA too. We use a pretty good one and do lots of advanced things with health checks both during a deploy and during an app lifecycle.

**Comment by mattmanning** [comment]
Closing this for now. Private networking is explained elsewhere, and we have new work queued for hardening/productionizing docs.

**Pull request closed without merging**
