### PR TITLE
api docs in convox site

### PR DESCRIPTION
**Pull request by ddollar**
screen shot 2016-04-22 at 2 24 26 pm

### CODE REVIEW

**Comment by mattmanning** [comment]
Looks pretty good, but it's kinda weird that there are form fields that don't do anything. Maybe we should just drop the Value column?

**Comment by mattmanning** [comment]
Also, I've found I need to set the correct Content-Type and Accept request headers to make API calls work correctly. I previously got those from the `curl` examples the old docs generated, but there's no mention of those here.

Also you need to set a Version header or set User-Agent to `curl/` to get things working. Can we just add a request headers section at the top or something?

**Comment by yuvaly** [comment]
If that’s true file it as a bug against rack and let’s fix it.

**Comment by ddollar** [comment]
If that's true let's file it as a bug against Rack. curl should work cleanly with only an Authorization header. The Version header is probably out of date anyway.

**Pull request merged**
