### PR TITLE
Blog formatting

### PR DESCRIPTION
**Pull request by mattmanning**
Removes right-justification to improve readability.

Before:
unspecified-15

After:
unspecified-14

## Release Playbook
- [x] Rebase against master
- [ ] Code review
- [ ] Merge into master
- [ ] Verify changes at http://site-staging.convox.com
- [ ] Promote release on `site-production` in the `convox/production` Rack

### CODE REVIEW

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Jwgx5rpa&#x2F;255-blog-formatting"> Blog formatting</a>

**Comment by yuvaly** [comment]
Can you give the screenshots in their full context with the surrounding
borders please.

**Comment by ddollar** [comment]
Can you give the screenshots in their full context with the surrounding borders please.

**Comment by ddollar** [comment]
Just tried this in web inspector. :-1: to the justification change, :+1: to everything else

**Comment by mattmanning** [comment]
@ddollar Will update screenshots. What problems are you seeing in web inspector? Looks good to me in Chrome and Safari.

**Comment by nzoschke** [comment]
👍 from me on the existing PR

**Comment by ddollar** [comment]
I don't like the left justification. The rest is good to go.

**Comment by mattmanning** [comment]
I'm gonna go ahead and merge the whole PR. I think the left-justified layout is clearly more readable as it removes irregular spacing between words.

**Pull request merged**
