### PR TITLE
Jobs page and 2 postings

### PR DESCRIPTION
**Pull request by mattmanning**
unspecified-1

unspecified-2

unspecified-3

### CODE REVIEW

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7XQes8ai&#x2F;51-add-jobs-page-to-convox-com-and-list-open-positions"> Add JOBS page to convox.com and list open positions</a>

**Comment by nzoschke** [comment]
+1 on everything here.

Here's a thought... Split `About Convox` into two paragraphs, the second something like:

> We are open to hiring diverse people located anywhere in the world. We value willingness to learn and consider mentorship around development and infrastructure best practices a key goal of Convox. We encourage anyone that wants to learn more about this space to reach out to discuss the opportunities at Convox.

I'm sure there's more prior art about good messaging here...

I'll also follow up to make the systems engineer position sound more approachable for junior engineers, or make another position.

**Comment by mattmanning** [comment]
@nzoschke Great suggestion, thanks. I added a paragraph like that with slightly tweaked language.

**Comment by ddollar** [comment]
Merged in #145

**Pull request closed without merging**
